# This is a basic workflow to help you get started with Actions

name: TF WhatsUp

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run TF WhatsUp
        run: |
          # download binary file https://github.com/SeanKilleen/tf-whatsup/releases/download/v0.11.1-alpha.0.1.1/tfwhatsup_linux-x64_sefcontained.tar.gz
          curl -L -o tfwhatsup.tar.gz https://github.com/SeanKilleen/tf-whatsup/releases/download/v0.11.1-alpha.0.1.1/tfwhatsup_linux-x64_sefcontained.tar.gz
          tar xzvf tfwhatsup.tar.gz

          ls -al

          # Run and ignore any errors
          ./TFWhatsUp.Console --all || true
        continue-on-error: true


      
